- name: Create Jekins JObs
  hosts: localhost
  connection: local
  vars:
    jobs:
      - roboshop-terraform
      - cart
      - catalogue
      - user
      - payment
      - shipping
      - frontend
  roles:
    - jenkins-jobs