- name: Setup Template
  ansible.builtin.template:
    src: sbranch.xml
    dest: /tmp/sbranch.xml

- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/sbranch.xml') }}"
    name: "{{ item }}"
    password: DevOps321
    url: http://172.31.23.176:8080
    user: admin